[project]
name = "buildgpt-from-zero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch==2.2.2",
    "torchaudio==2.2.2",
    "torchvision==0.17.2",
]
